Add infrastructure permissions docs
gardener/gardener-extension-provider-gcp pull request #161
Opened 2020-08-24 16:28 UTC by danielfoehrKn

**How to categorize this PR?**

/area documentation
/kind enhancement
/priority normal
/platform gcp

**What this PR does / why we need it**:

Add infrastructure permissions docs.

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```improvement operator

```

2020-08-25 03:57 UTC, DockToFuture requested changes

2020-08-25 03:57 UTC, DockToFuture commented on docs/usage-as-end-user.md
> +The required credentials for the GCP project are a [Service Account Key](https://cloud.google.com/iam/docs/service-accounts#service_account_keys)) to authenticate as a [GCP Service Account](https://c
just a small typo, remove one ")"

2020-08-25 03:58 UTC, DockToFuture requested changes

2020-08-25 03:58 UTC, DockToFuture commented on docs/usage-as-end-user.md
> +The `SecretBinding` is configurable in the [Shoot cluster](https://github.com/gardener/gardener/blob/master/example/90-shoot.yaml)) with the field `secretBindingName`.
just a small typo, remove one ")"

2020-08-25 05:53 UTC, rfranzke reviewed
Looks great after addressing the nit mentioned by @DockToFuture

2020-08-25 06:03 UTC, prashanth26 reviewed
Thanks for the PR. Looks great. Minor suggestions.

2020-08-25 06:03 UTC, prashanth26 commented on docs/usage-as-operator.md
> +In this section we are describing how the configuration for `CloudProfile`s looks like for GCP and provide an example `CloudProfile` manifest with minimal configuration that you can use to allow crea
```suggestion
In this section, we are describing how the configuration for `CloudProfile`s looks like for GCP and provide an example `CloudProfile` manifest with a minimal configuration that you can use to allow creating GCP shoot clusters.
```

2020-08-25 07:46 UTC, prashanth26 approved these changes
/lgtm

2020-08-25 10:19 UTC, rfranzke approved these changes

2020-08-25 12:57 UTC, DockToFuture commented on docs/usage-as-end-user.md
> +The required credentials for the GCP project are a [Service Account Key](https://cloud.google.com/iam/docs/service-accounts#service_account_keys)) to authenticate as a [GCP Service Account](https://c
Can you please remove one ")"?

2020-08-27 14:52 UTC, rfranzke approved these changes

2020-08-28 05:50 UTC, DockToFuture approved these changes
/lgtm

2020-08-28 05:51 UTC, merged