Drop support for kubernetes < 1.20 for GCP extension provider
gardener/gardener-extension-provider-gcp pull request #533
Opened 2022-12-06 07:16 UTC by dimitar-kostadinov

**How to categorize this PR?**

/area open-source
/kind cleanup
/platform gcp

**What this PR does / why we need it**:
Drop support for kubernetes < 1.20 for GCP extension provider

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/6911

**Special notes for your reviewer**:

**Release note**:

```other operator
provider-gcp no longer supports Shoots with Кubernetes version < 1.20.
```

2022-12-07 10:55 UTC, MartinWeindel requested changes
Thanks for the nice PR. I already made use of it as a template for preparing a similar PR for provider-aws.

I have only one minor change request.

2022-12-07 10:55 UTC, MartinWeindel commented on pkg/webhook/controlplane/ensurer.go
> +	c.Command = extensionswebhook.EnsureStringWithPrefixContains(c.Command, "--disable-admission-plugins=",
Strange diff, but correct (see original line 205) :-)

2022-12-08 09:49 UTC, MartinWeindel approved these changes
/lgtm

2022-12-09 07:01 UTC, MartinWeindel approved these changes
/lgtm

2022-12-11 17:30 UTC, ialidzhikov requested changes

2022-12-11 17:30 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
> +func (e *ensurer) InjectClient(_ client.Client) error {
You could remove the whole `InjectClient` func as the ensurer no longer needs a client.

2022-12-16 13:16 UTC, ialidzhikov commented
/assign

2022-12-16 14:49 UTC, ialidzhikov reviewed
Looks good! Thank you for the clean up! Minor suggestion inline.

2022-12-16 14:49 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
> +	c.VolumeMounts = extensionswebhook.EnsureNoVolumeMountWithName(c.VolumeMounts, cloudProviderSecretVolumeMount.Name)
Assuming that all clusters are now running at least K8s 1.20 and the CSI migration was complete for them in 1.18 we can clean up these `EnsureNoVolumeMountWithName` calls.

Previously the handling was:
https://github.com/gardener/gardener-extension-provider-gcp/blob/38db4bac5eadeba6b5aa7f4763e09fe87cde4416/pkg/webhook/controlplane/ensurer.go#L360-L369

Prior to CSI we were ensuring volume and volume mount for the cloud-provider-config ConfigMap for components like the kube-apiserver, kube-controller-manager. With CSI we no longer need this volume and volume mount, hence we were ensuring that any potential present volume/volume mount gets cleaned up after the update to a version that enables CSI.
I think it should be safe to drop these `EnsureNoVolumeMountWithName` calls for the cloud-provider-config ConfigMap as they should be already cleaned up from the kube-apiserver/kube-controller-manager deployments after CSI migration is complete. And today there shouldn't be any handling that adds these cloud-provider-config volume and volume mount.

2022-12-16 14:49 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
> +	c.VolumeMounts = extensionswebhook.EnsureNoVolumeMountWithName(c.VolumeMounts, cloudProviderSecretVolumeMount.Name)
Same as the above comment for the kube-apiserver.

2022-12-16 14:49 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
> +		delete(template.Annotations, "checksum/configmap-"+internal.CloudProviderConfigName)
This handling also could be removed when we drop the `EnsureNoVolumeMountWithName` handling for the cloud-provider-config ConfigMap.

2022-12-16 15:16 UTC, ialidzhikov commented on pkg/controller/controlplane/valuesprovider.go
> +			"enabled": true,
Is it possible to change the default value to true here
https://github.com/gardener/gardener-extension-provider-gcp/blob/310dd84ac7159cb4009d429bf55d9af5e48ddb86/charts/internal/shoot-crds/values.yaml#L1-L2
and to drop this `GetControlPlaneShootCRDsChartValues` func?

We could also adapt https://github.com/gardener/gardener-extension-provider-gcp/blob/9c55612de3c5bf27e4f7086a4b39d826aa7b7e30/charts/internal/seed-controlplane/values.yaml#L6-L7 - the csi-driver-controller chart to be enabled by default.

2022-12-21 08:04 UTC, dimitar-kostadinov commented
/retest-required

2022-12-21 08:09 UTC, dimitar-kostadinov commented
/retest

2022-12-21 10:00 UTC, ialidzhikov approved these changes
/lgtm

2023-01-18 15:27 UTC, kon-angelo commented
/reviewed ok-to-test

2023-01-18 15:31 UTC, kon-angelo approved these changes
/lgtm
/reviewed ok-to-test

2023-01-18 15:32 UTC, kon-angelo commented
/unhold

2023-01-30 12:11 UTC, ialidzhikov commented
/needs rebase

2023-01-31 07:51 UTC, kon-angelo approved these changes
/lgtm

2023-01-31 07:52 UTC, ialidzhikov approved these changes
/lgtm

2023-01-31 07:52 UTC, merged