Vendor `@gardenerv1.71.1`
gardener/gardener-extension-provider-gcp pull request #604
Opened 2023-05-30 04:53 UTC by ary1992

**How to categorize this PR?**

/area open-source
/kind enhancement
/platform gcp

**What this PR does / why we need it**:
Vendor gardener v1.71.2

**Which issue(s) this PR fixes**:
Prerequisite for: https://github.com/gardener/gardener/issues/7783

**Special notes for your reviewer**:

**Release note**:

```other dependency
The following dependency is updated:
- github.com/gardener/gardener: v1.70.2 -> v1.71.2
```

2023-06-01 04:36 UTC, shafeeqes commented on pkg/webhook/controlplane/ensurer.go
> +	k8sGreaterEqual127, _ := version.CompareVersions(cluster.Shoot.Spec.Kubernetes.Version, ">=", "1.27")
Handle error

2023-06-09 13:17 UTC, ialidzhikov requested changes
Same as https://github.com/gardener/gardener-extension-provider-azure/pull/693#pullrequestreview-1471970645.
I would suggest to split the K8s 1.27 support to a dedicated PR.

2023-06-09 13:17 UTC, ialidzhikov commented on charts/images.yaml
> +  targetVersion: ">= 1.26.x"
```suggestion
  targetVersion: "1.26.x"
```

:)

2023-06-09 13:17 UTC, ialidzhikov commented on charts/images.yaml
>    sourceRepository: github.com/gardener/cloud-provider-gcp
Please incorporate all the gcp CCM versions released in https://github.com/gardener/gardener/issues/7783.

2023-06-09 13:17 UTC, ialidzhikov commented on pkg/webhook/controlplane/ensurer.go
> +	k8sGreaterEqual127, err := version.CompareVersions(cluster.Shoot.Spec.Kubernetes.Version, ">=", "1.27")
Please, check my comments in https://github.com/gardener/gardener-extension-provider-aws/pull/759. They apply for this file as well.

2023-06-09 13:26 UTC, kon-angelo commented on charts/images.yaml
> +  tag: "v1.9.4"
We downgraded the version in the current master anyway because there was no image published even if there was a github release.

2023-06-09 13:56 UTC, ialidzhikov commented on charts/images.yaml
> +  tag: "v1.9.4"
Ok, thanks. Then a rebase is needed to get this not related diff fixed.

2023-06-12 13:58 UTC, ialidzhikov approved these changes
/lgtm

2023-06-12 15:16 UTC, ialidzhikov commented
/test

2023-06-16 11:11 UTC, rfranzke commented
Could you bump directly to `v1.73.0` now that it got released?

2023-06-19 06:00 UTC, rfranzke commented
Can you check the failing `verify` step, please?

2023-06-19 08:58 UTC, kon-angelo approved these changes
/lgtm

2023-06-19 09:10 UTC, merged