add node template support
gardener/gardener-extension-provider-gcp pull request #748
Opened 2024-04-29 06:58 UTC by kon-angelo

**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform gcp

**What this PR does / why we need it**:

**Which issue(s) this PR fixes**:
Fixes #

**Special notes for your reviewer**:
See https://github.com/gardener/gardener/issues/4948 for similar PRs

**Release note**:

```other operator
Provider-gcp now supports node template configuration for the workerpools. 
```

2024-04-29 10:37 UTC, hebelsan requested changes

2024-04-29 10:37 UTC, hebelsan commented on pkg/apis/gcp/validation/worker.go
> +		allErrs = append(allErrs, validateResourceQuantityValue(capacityAttribute, value, fldPath.Child("nodeTemplate").Child("capacity").Child(string(capacityAttribute)))...)
same here.

2024-04-29 10:37 UTC, hebelsan commented on pkg/controller/worker/machines.go
> +				numGpus := workerConfig.NodeTemplate.Capacity[ResourceGPU]
couldn't `workerConfig.NodeTemplate` be nil here?

2024-05-21 08:53 UTC, kon-angelo commented on pkg/apis/gcp/validation/worker.go
> +			allErrs = append(allErrs, field.Required(fldPath.Child("nodeTemplate").Child("capacity"), fmt.Sprintf("%s is a mandatory field", capacityAttribute)))
Good catch

2024-05-29 16:48 UTC, hebelsan approved these changes
/lgtm

2024-05-29 17:05 UTC, hebelsan approved these changes

2024-05-30 10:56 UTC, merged