Adjustments for deploying extension on Garden runtime cluster by gardener-operator
gardener/gardener-extension-provider-gcp pull request #905
Opened 2024-11-18 15:07 UTC by oliver-goetz

**How to categorize this PR?**

/area control-plane
/kind enhancement
/platform gcp

**What this PR does / why we need it**:
This PR enables the extension to be deployed via `extensions.operator.gardener.cloud` CRD. It includes minor changes in code and a refactoring of the Helm charts.

**Which issue(s) this PR fixes**:
Part of https://github.com/gardener/gardener/issues/9635

**Special notes for your reviewer**:

**Release note**:

```feature operator
The extension can now be deployed via `extensions.operator.gardener.cloud` CRD.
```
```breaking operator
`gardener-extension-admission-gcp` Helm chart has been removed. The admission can be deployed by applying `admission-gcp-application` and `admission-gcp-runtime` charts separately. With this change the `global` structure in Helm values of these charts has been removed. Still supported settings have been moved to other sections.
```

2024-11-20 11:52 UTC, MartinWeindel requested changes
Thanks for the adjustments. 🙂
There are some latest changes in the similar PR for `provider-aws` applying also here.

2024-11-20 11:52 UTC, MartinWeindel commented on charts/gardener-extension-admission-gcp/charts/application/templates/rbac.yaml
> +  - update
Looks as if these changes have been applied by mistake in the provider-aws.
Please also remove them. See https://github.com/gardener/gardener-extension-provider-aws/pull/1100#pullrequestreview-2447758364
```suggestion
```

2024-11-20 11:52 UTC, MartinWeindel commented on charts/gardener-extension-provider-gcp/templates/deployment.yaml
> +        - --disable-controllers=backupentry,bastion,controlplane,infrastructure,worker,healthcheck
Improvement suggested by @timuthy 
```suggestion
        - --controllers=backupbucket,dnsrecord
```

2024-11-20 11:52 UTC, MartinWeindel commented on cmd/gardener-extension-provider-gcp/app/app.go
> +			reconcileOpts.Completed().Apply(&gcpdnsrecord.DefaultAddOptions.IgnoreOperationAnnotation, &gcpdnsrecord.DefaultAddOptions.ExtensionClass)
Extension class is also needed for `BackupBucket`.
```suggestion
			reconcileOpts.Completed().Apply(&gcpdnsrecord.DefaultAddOptions.IgnoreOperationAnnotation, &gcpdnsrecord.DefaultAddOptions.ExtensionClass)
			reconcileOpts.Completed().Apply(&gcpbackupbucket.DefaultAddOptions.IgnoreOperationAnnotation, &gcpbackupbucket.DefaultAddOptions.ExtensionClass)
```

2024-12-06 13:09 UTC, AndreasBurger approved these changes

2024-12-06 13:09 UTC, merged